[build]
  # Comanda a Netlify a entrar na pasta frontend e a compilar o layout
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[functions]
  # Indica à Netlify que a tua pasta de backend/funções da API é a "api"
  directory = "../api"

[[redirects]]
  # Encaminha todos os pedidos de /api/* para o teu backend
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  # Trata as rotas do React/Vite para evitar o erro 404
  from = "/*"
  to = "/index.html"
  status = 200