@startuml Geral-simplificado.puml
!theme plain
left to right direction
skinparam packageStyle rectangle

actor "User" as U
actor "System Administrator" as A

rectangle "Skin Lesion Gamification Web Platform" as App

U --> App : Uses platform features
A --> App : Manages system & content
@enduml